# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#this is a single line comment
"""this is a multi comment
also called a docstring"""
print("DATA TYPE AND VARIABLES")
#numbers
age = 21 #integer
price = 99.99 #float
complex_number = 2 + 3j #complex number

#text
name = "Anurodh" #string
greeting = 'hello,world'

#boolean
is_student = True #boolean

has_job = False #boolean

#display variable and their types
print(f"Name: {name}, Type: {type(name)}")
print(f"Age: {age}, Type: {type(age)}")
print(f"Price: {price}, Type: {type(price)})")
print(f"Is Student: {is_student}, Type: {type(is_student)}")


# 3. type conversion

print("\n" + "="*50)
print("TYPE CONVERSION")
print("="*50)

#string to Integer
num_str="100"
num_int=int(num_str)
print(f'converting"{num_str}" to integer : {num_int}')

#integer to float
num_float = float(age)
print(f"Converting{age} to float :{num_float}")

#number to string
pi = 3.14159
pi_str = str(pi)
print(f"converting {pi} to string : {pi_str}")

# 4. string operations

print("\n"+"="*50)
print("STRING OPERATIONS")
print("="*50)

greeting = " hello"
name = "Bob"

#string concatenation
combined = greeting + " " + name
print(f"concatenation:{combined}")

#string repetition
laugh = "HA" * 10
print(f"repetition : {laugh}")

# string methods
text = " Python Programming "
print(f"Original text: '{text}'")
print(f"strip whitespace: '{text.strip()}'")
print(f"Lowercase: '{text.lower()}'")
print(f"Uppercase: '{text.upper()}'")
print(f"Replace python with java: '{text.replace('Python', 'Java')}'")
print(f"Split into words: {text.split()}")


# string formatting(f-strings)
print("\n STRING FORMATTING (f-strings)")
name = "Subodh"
score = 95.5
print(f"student: {name}, scored {score}")

# string slicing
print("\n STRING SLICING")
word = "Programming"
print(f"Word: {word}")
print(f" First 3 characters: {word[:3]}")
print(f" Last 3 characters: {word[-3:]}")
print(f" Reversed: {word[::-1]}")

# Basic operations
print( "*" *30)
print("\n BASIC OPERATIONS")
print( "*" *30)

a = 10
b = 3

# Arithmetic operations
print("-" *30)
print("\n ARITHMETIC OPERATIONS")
print("-" *30)
print(f"a:{a}, b:{b}")
print(f"Addition: {a} + {b} = {a + b}")
print(f"Subtraction: {a} - {b} = {a - b}")
print(f"Multiplication: {a} * {b} = {a * b}")
print(f"Division: {a} / {b} = {a / b}")
print(f"Modulus: {a} % {b} = {a % b}")
print(f"Exponentiation: {a} ** {b} = {a ** b}")

# Comparison operations
print("-" *30)
print("\n COMPARISON OPERATIONS")
print("-" *30)
print(f"{a}=={b}: {a==b}")
print(f"{a}!={b}: {a!=b}")
print(f"{a}>{b}: {a>b}")
print(f"{a}< {b}: {a} = {b}: {a>=b}")
print(f"{a}<={b}: {a<=b}")